name: weather_pro
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  provider: ^4.0.5+1
  geolocator: ^5.3.1
  flutter_icons: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^4.0.1
  device_preview: ^0.4.4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
